
ALTER TABLE public.employee_messages 
ADD COLUMN IF NOT EXISTS reopened_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS reopened_by UUID,
ADD COLUMN IF NOT EXISTS reopen_count INTEGER DEFAULT 0;
