import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useLanguage } from '@/contexts/LanguageContext';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { toast } from 'sonner';
import { Loader2, Search, Star, X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface Supplier {
  id: string;
  name: string;
  email: string | null;
  category: string;
  is_preferred: boolean;
}

interface CreateRFQModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  prId: string;
  prType: 'material' | 'service';
  prNumber: string;
}

export default function CreateRFQModal({ 
  open, 
  onOpenChange, 
  prId, 
  prType, 
  prNumber 
}: CreateRFQModalProps) {
  const navigate = useNavigate();
  const { language } = useLanguage();
  
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [selectedSuppliers, setSelectedSuppliers] = useState<string[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    if (open) {
      fetchSuppliers();
      setSelectedSuppliers([]);
      setNotes('');
      setSearchQuery('');
    }
  }, [open]);

  const fetchSuppliers = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('suppliers')
        .select('id, name, email, category, is_preferred')
        .order('is_preferred', { ascending: false })
        .order('name');

      if (error) throw error;
      setSuppliers((data || []) as Supplier[]);
    } catch (error) {
      console.error('Error fetching suppliers:', error);
      toast.error(language === 'el' ? 'Αποτυχία φόρτωσης προμηθευτών' : 'Failed to load suppliers');
    } finally {
      setLoading(false);
    }
  };

  const getCategoryForPR = () => {
    return prType === 'material' ? 'materials' : 'services';
  };

  const handleQuickSelect = () => {
    const category = getCategoryForPR();
    const preferred = suppliers.filter(s => 
      s.is_preferred && (s.category === category || s.category === 'both')
    );
    const toSelect = preferred.slice(0, 5).map(s => s.id);
    setSelectedSuppliers(toSelect);
    toast.info(
      language === 'el' 
        ? `Επιλέχθηκαν ${toSelect.length} προτιμώμενοι προμηθευτές` 
        : `Selected ${toSelect.length} preferred suppliers`
    );
  };

  const handleClearSelection = () => {
    setSelectedSuppliers([]);
  };

  const toggleSupplier = (supplierId: string) => {
    setSelectedSuppliers(prev => 
      prev.includes(supplierId)
        ? prev.filter(id => id !== supplierId)
        : [...prev, supplierId]
    );
  };

  const filteredSuppliers = suppliers.filter(s => {
    const matchesSearch = s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         s.email?.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = s.category === getCategoryForPR() || s.category === 'both';
    return matchesSearch && matchesCategory;
  });

  const handleCreateRFQ = async () => {
    if (selectedSuppliers.length === 0) {
      toast.error(
        language === 'el' 
          ? 'Επιλέξτε τουλάχιστον έναν προμηθευτή' 
          : 'Select at least one supplier'
      );
      return;
    }

    try {
      setCreating(true);

      // Create RFQ
      const { data: rfqData, error: rfqError } = await supabase
        .from('rfqs')
        .insert([{
          pr_id: prId,
          status: 'draft',
          rfq_number: '', // Auto-generated by trigger
          deadline: null,
        }])
        .select()
        .single();

      if (rfqError) throw rfqError;

      // Create RFQ suppliers
      const rfqSuppliersData = selectedSuppliers.map(supplierId => ({
        rfq_id: rfqData.id,
        supplier_id: supplierId,
        status: 'sent',
      }));

      const { error: suppliersError } = await supabase
        .from('rfq_suppliers')
        .insert(rfqSuppliersData);

      if (suppliersError) throw suppliersError;

      // Update PR status to rfq_sent
      const { error: prError } = await supabase
        .from('purchase_requests')
        .update({ status: 'rfq_sent' })
        .eq('id', prId);

      if (prError) throw prError;

      toast.success(
        language === 'el' 
          ? 'RFQ δημιουργήθηκε επιτυχώς' 
          : 'RFQ created successfully'
      );

      onOpenChange(false);
      navigate(`/procurement/rfqs/${rfqData.id}`);
    } catch (error: any) {
      console.error('Error creating RFQ:', error);
      toast.error(error.message || (language === 'el' ? 'Αποτυχία δημιουργίας RFQ' : 'Failed to create RFQ'));
    } finally {
      setCreating(false);
    }
  };

  const quickSelectLabel = prType === 'material'
    ? (language === 'el' ? 'Γρήγορη επιλογή: Κορυφαίοι Προμηθευτές Υλικών' : 'Quick select: Top Materials Suppliers')
    : (language === 'el' ? 'Γρήγορη επιλογή: Κορυφαίοι Υπεργολάβοι' : 'Quick select: Top Subcontractors');

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>
            {language === 'el' ? 'Δημιουργία RFQ' : 'Create RFQ'}
          </DialogTitle>
          <p className="text-sm text-muted-foreground">
            {language === 'el' ? 'Για αίτημα' : 'For request'}: {prNumber}
          </p>
        </DialogHeader>

        <div className="flex-1 overflow-auto space-y-4">
          {/* Quick Actions */}
          <div className="flex flex-wrap gap-2">
            <Button 
              type="button" 
              variant="outline" 
              size="sm"
              onClick={handleQuickSelect}
            >
              <Star className="h-4 w-4 mr-2" />
              {quickSelectLabel}
            </Button>
            <Button 
              type="button" 
              variant="outline" 
              size="sm"
              onClick={handleClearSelection}
            >
              <X className="h-4 w-4 mr-2" />
              {language === 'el' ? 'Καθαρισμός επιλογής' : 'Clear selection'}
            </Button>
          </div>

          {/* Supplier Selection */}
          <div className="space-y-2">
            <Label>
              {language === 'el' ? 'Επιλογή Προμηθευτών' : 'Select Suppliers'} *
              <span className="ml-2 text-muted-foreground">
                ({selectedSuppliers.length} {language === 'el' ? 'επιλεγμένοι' : 'selected'})
              </span>
            </Label>
            
            {/* Search */}
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder={language === 'el' ? 'Αναζήτηση προμηθευτών...' : 'Search suppliers...'}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>

            {/* Supplier List */}
            <div className="border rounded-md max-h-[200px] overflow-auto">
              {loading ? (
                <div className="flex items-center justify-center p-4">
                  <Loader2 className="h-6 w-6 animate-spin" />
                </div>
              ) : filteredSuppliers.length === 0 ? (
                <div className="p-4 text-center text-muted-foreground">
                  {language === 'el' ? 'Δεν βρέθηκαν προμηθευτές' : 'No suppliers found'}
                </div>
              ) : (
                filteredSuppliers.map(supplier => (
                  <div 
                    key={supplier.id}
                    className={cn(
                      "flex items-center gap-3 p-3 border-b last:border-b-0 cursor-pointer hover:bg-muted/50",
                      selectedSuppliers.includes(supplier.id) && "bg-primary/5"
                    )}
                    onClick={() => toggleSupplier(supplier.id)}
                  >
                    <Checkbox 
                      checked={selectedSuppliers.includes(supplier.id)}
                      onCheckedChange={() => toggleSupplier(supplier.id)}
                    />
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{supplier.name}</span>
                        {supplier.is_preferred && (
                          <Star className="h-4 w-4 text-yellow-500 fill-yellow-500" />
                        )}
                      </div>
                      {supplier.email && (
                        <span className="text-sm text-muted-foreground">{supplier.email}</span>
                      )}
                    </div>
                    <Badge variant="outline" className="text-xs">
                      {supplier.category === 'materials' 
                        ? (language === 'el' ? 'Υλικά' : 'Materials')
                        : supplier.category === 'services'
                        ? (language === 'el' ? 'Υπηρεσίες' : 'Services')
                        : (language === 'el' ? 'Και τα δύο' : 'Both')}
                    </Badge>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* Notes */}
          <div className="space-y-2">
            <Label>
              {language === 'el' ? 'Μήνυμα / Σημειώσεις προς προμηθευτή (προαιρετικό)' : 'Message / Notes to supplier (optional)'}
            </Label>
            <Textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder={language === 'el' ? 'Προσθέστε τυχόν σημειώσεις...' : 'Add any notes...'}
              rows={3}
            />
          </div>
        </div>

        <DialogFooter className="mt-4">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            {language === 'el' ? 'Ακύρωση' : 'Cancel'}
          </Button>
          <Button onClick={handleCreateRFQ} disabled={creating || selectedSuppliers.length === 0}>
            {creating && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
            {language === 'el' ? 'Δημιουργία RFQ' : 'Create RFQ'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
